### ISSUE TITLE
Looping each, find...

### ISSUE THREAD

**Issue by Heterotroph** [Hedronium/LinkedList.js#1]
Hi, please fix this bug:
`nodes.tail().setNext(nodes.head());
 
nodes.head().setPrevious(nodes.tail());
 
nodes.find("...") //`

**Comment by omranjamal** [comment]
So what I understand is, this is allowing circular lists to exist?

**Comment by Heterotroph** [comment]
Yes, I used your library that way. But when creating a looped linked-list, there are problems in methods each, find...
I downloaded your implementation from npm.

Sorry for my english.


Ruslan Akhtyamov
Call
Send SMS
Add to Skype
You'll need Skype CreditFree via Skype


________________________________
От: Omran Jamal <notifications@github.com>
Отправлено: 29 марта 2017 г. 9:36
Кому: Hedronium/LinkedList.js
Копия: Ruslan Akhtyamov; Author
Тема: Re: [Hedronium/LinkedList.js] Looping each, find... (#1)


So what I understand is, this is allowing circular lists to exist?
